# Generated by Django 4.2.5 on 2023-09-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbooks', '0005_author_alter_book_autore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='autore',
        ),
        migrations.AddField(
            model_name='book',
            name='autore',
            field=models.ManyToManyField(to='appbooks.author'),
        ),
    ]
