# Generated by Django 4.2.5 on 2023-09-07 15:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appbooks', '0006_remove_book_autore_book_autore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nazionalita',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
