# Generated by Django 4.2.5 on 2023-09-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbooks', '0007_alter_author_nazionalita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField()),
                ('autore_frase', models.CharField(max_length=100)),
                ('pagina', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='quotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appbooks.quote'),
        ),
    ]
