# Generated by Django 4.2.5 on 2023-09-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbooks', '0008_quote_book_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quotes',
        ),
        migrations.AddField(
            model_name='book',
            name='quotes',
            field=models.ManyToManyField(to='appbooks.quote'),
        ),
    ]
