# Generated by Django 4.2.5 on 2023-09-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbooks', '0009_remove_book_quotes_book_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='appbooks.quote'),
        ),
    ]
